import {test,expect} from '@playwright/test';
test('Study, saved notes, quiz, 3D matching, and complete offline reload',async({page,context})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await expect(page.getByText('Preparing the anatomy')).toBeHidden({timeout:60000});await expect(page.getByRole('alert')).toHaveCount(0);
 await page.getByRole('button',{name:'RMT Study',exact:true}).click();
 const study=page.getByRole('region',{name:'RMT study'});
 await expect(study.getByRole('heading',{name:'Trapezius',exact:true})).toBeVisible();
 await study.getByRole('button',{name:'Show in 3D'}).click();
 await study.getByLabel('Region',{exact:true}).selectOption('Leg');
 await expect(study.getByRole('heading',{name:'Gastrocnemius',exact:true})).toBeVisible();
 await study.getByLabel('Region',{exact:true}).selectOption('All');
 await study.getByLabel('Muscle',{exact:true}).selectOption('Latissimus dorsi');
 await expect(study.getByRole('heading',{name:'Latissimus dorsi',exact:true})).toBeVisible();
 await expect(study.getByText('No corresponding mesh in this dataset.')).toBeVisible();
 await study.getByLabel('Muscle',{exact:true}).selectOption('Trapezius');
 await expect(page.getByRole('heading',{name:'Trapezius',exact:true}).last()).toBeVisible();
 await study.getByRole('button',{name:'Save favorite'}).click();
 await study.getByRole('textbox',{name:'My study notes'}).fill('Review scapular upward rotation.');
 await study.getByRole('button',{name:'quiz',exact:true}).click();await study.getByRole('button',{name:'Reveal answer'}).click();await study.getByRole('button',{name:'I knew it'}).click();
 await expect(study.getByText('1 / 1 recalled',{exact:false})).toBeVisible();
 const downloadPromise=page.waitForEvent('download');
 await study.getByRole('button',{name:'Export study backup'}).click();
 const download=await downloadPromise;
 expect(download.suggestedFilename()).toBe('halo-anatomy-study.json');
 const backup=JSON.parse(await (await import('node:fs/promises')).readFile((await download.path())!,'utf8'));
 expect(backup.notes.Trapezius).toBe('Review scapular upward rotation.');
 await study.locator('input[type=file]').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{}')});
 await expect(study.getByRole('status')).toHaveText('Invalid backup. Your existing study data was kept.');
 await study.getByRole('button',{name:'reference',exact:true}).click();
 await study.locator('input[type=file]').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...backup,notes:{Trapezius:'Restored note.'}}))});
 await expect(study.getByRole('textbox',{name:'My study notes'})).toHaveValue('Restored note.');
 await page.evaluate(async()=>{await navigator.serviceWorker.ready;});
 await context.setOffline(true);await page.reload();
 await expect(page.getByText('Preparing the anatomy')).toBeHidden({timeout:60000});await expect(page.getByRole('alert')).toHaveCount(0);
 await page.getByRole('button',{name:'RMT Study',exact:true}).click();
 await expect(study.getByRole('textbox',{name:'My study notes'})).toHaveValue('Restored note.');
 await study.getByRole('button',{name:'favorites',exact:true}).click();await expect(study.getByRole('heading',{name:'Trapezius'})).toBeVisible();
 await page.setViewportSize({width:390,height:844});await expect(study).toBeVisible();
 expect(errors).toEqual([]);
});
