export interface RmtStudyEntry {name:string;origin:string;insertion:string;action:string;innervation:string;region:string;note?:string}
export const RMT_STUDY:RmtStudyEntry[]=[
{name:'Trapezius',region:'Neck / back',origin:'External occipital protuberance, medial superior nuchal line, nuchal ligament, spinous processes C7–T12',insertion:'Lateral clavicle, acromion and spine of scapula',action:'Upper fibres elevate and upwardly rotate scapula; middle fibres retract; lower fibres depress and assist upward rotation',innervation:'Spinal accessory nerve (CN XI), with C3–C4 sensory/proprioceptive contributions'},
{name:'Sternocleidomastoid',region:'Neck',origin:'Manubrium and medial clavicle',insertion:'Mastoid process and lateral superior nuchal line',action:'Unilateral: ipsilateral lateral flexion and contralateral rotation. Bilateral: cervical flexion; assists inspiration',innervation:'Spinal accessory nerve (CN XI), C2–C3 sensory/proprioceptive contributions'},
{name:'Deltoid',region:'Shoulder',origin:'Lateral clavicle, acromion and spine of scapula',insertion:'Deltoid tuberosity of humerus',action:'Middle fibres abduct shoulder; anterior fibres flex and internally rotate; posterior fibres extend and externally rotate',innervation:'Axillary nerve (C5–C6)'},
{name:'Supraspinatus',region:'Shoulder',origin:'Supraspinous fossa of scapula',insertion:'Superior facet of greater tubercle of humerus',action:'Initiates shoulder abduction and contributes to glenohumeral stability',innervation:'Suprascapular nerve (C5–C6)'},
{name:'Infraspinatus',region:'Shoulder',origin:'Infraspinous fossa of scapula',insertion:'Middle facet of greater tubercle of humerus',action:'Externally rotates shoulder and stabilizes humeral head',innervation:'Suprascapular nerve (C5–C6)'},
{name:'Teres minor',region:'Shoulder',origin:'Lateral border of scapula',insertion:'Inferior facet of greater tubercle of humerus',action:'External rotation and weak adduction of shoulder; stabilizes humeral head',innervation:'Axillary nerve (C5–C6)'},
{name:'Subscapularis',region:'Shoulder',origin:'Subscapular fossa',insertion:'Lesser tubercle of humerus',action:'Internal rotation and adduction of shoulder; stabilizes humeral head',innervation:'Upper and lower subscapular nerves (C5–C7)'},
{name:'Pectoralis major',region:'Chest / shoulder',origin:'Medial clavicle, sternum and upper costal cartilages',insertion:'Lateral lip of intertubercular sulcus of humerus',action:'Adducts and internally rotates humerus; clavicular fibres flex shoulder',innervation:'Lateral and medial pectoral nerves (C5–T1)'},
{name:'Latissimus dorsi',region:'Back / shoulder',origin:'Lower thoracic spinous processes, thoracolumbar fascia, iliac crest and lower ribs',insertion:'Floor of intertubercular sulcus of humerus',action:'Extends, adducts and internally rotates humerus',innervation:'Thoracodorsal nerve (C6–C8)'},
{name:'Biceps brachii',region:'Arm',origin:'Long head: supraglenoid tubercle; short head: coracoid process',insertion:'Radial tuberosity and bicipital aponeurosis',action:'Supinates forearm and flexes elbow; assists shoulder flexion',innervation:'Musculocutaneous nerve (C5–C6)'},
{name:'Triceps brachii',region:'Arm',origin:'Long head: infraglenoid tubercle; lateral and medial heads: posterior humerus',insertion:'Olecranon of ulna',action:'Extends elbow; long head also assists shoulder extension and adduction',innervation:'Radial nerve (C6–C8)'},
{name:'Gluteus maximus',region:'Hip',origin:'Posterior ilium, sacrum, coccyx and sacrotuberous ligament',insertion:'Iliotibial tract and gluteal tuberosity',action:'Extends and externally rotates hip; assists rising and powerful locomotion',innervation:'Inferior gluteal nerve (L5–S2)'},
{name:'Gluteus medius',region:'Hip',origin:'External ilium between anterior and posterior gluteal lines',insertion:'Lateral surface of greater trochanter',action:'Abducts hip and stabilizes pelvis during single-leg stance; anterior fibres assist internal rotation',innervation:'Superior gluteal nerve (L4–S1)'},
{name:'Piriformis',region:'Hip',origin:'Anterior sacrum',insertion:'Superior border of greater trochanter',action:'Externally rotates extended hip; abducts flexed hip; contributes to hip stability',innervation:'Nerve to piriformis (S1–S2)'},
{name:'Rectus femoris',region:'Thigh',origin:'Anterior inferior iliac spine and ilium superior to acetabulum',insertion:'Tibial tuberosity through quadriceps tendon, patella and patellar ligament',action:'Extends knee and flexes hip',innervation:'Femoral nerve (L2–L4)'},
{name:'Biceps femoris',region:'Posterior thigh',origin:'Long head: ischial tuberosity; short head: linea aspera and lateral supracondylar line',insertion:'Head of fibula',action:'Flexes knee and externally rotates flexed leg; long head extends hip',innervation:'Long head: tibial division; short head: common fibular division of sciatic nerve (L5–S2)'},
{name:'Gastrocnemius',region:'Leg',origin:'Posterior femoral condyles',insertion:'Posterior calcaneus via calcaneal tendon',action:'Plantarflexes ankle and assists knee flexion',innervation:'Tibial nerve (S1–S2)'},
{name:'Soleus',region:'Leg',origin:'Posterior fibular head/proximal fibula and soleal line of tibia',insertion:'Posterior calcaneus via calcaneal tendon',action:'Plantarflexes ankle; important postural muscle',innervation:'Tibial nerve (S1–S2)'}
];
export function rmtStudyFor(name?:string){
 if(!name)return undefined;
 const n=name.toLowerCase().replace(/\b(left|right|muscle)\b/g,'').replace(/\s+/g,' ').trim();
 if(!n)return undefined;
 return RMT_STUDY.find(x=>n===x.name.toLowerCase()||n.endsWith(' of '+x.name.toLowerCase()) && !n.startsWith('zone of '));
}
